### ISSUE TITLE
docker

### ISSUE THREAD

**Issue by rafipiccolo** [subnub/myDrive#11]
Hello,

Could you publish a docker image / or a docker file + docker compose ?

I would love the easy deploy and monitoring.
I can help maybe.

**Comment by subnub** [comment]
We are currently working on a docker image, but currently we are still ironing out a few issues with it. You can see the current progress in the docker-test branch: https://github.com/subnub/myDrive/tree/docker-testing

This has the docker build file, you are welcome to give a try, the main issue seems to be connecting to mongoDB, and we would gladly take any help me can get! I do not personally know much about docker, so I am having someone help me with it (as you can see by the commits).

**Comment by rafipiccolo** [comment]
Usually i dont use "network : host"

Then, when you have 2 containers you cannot use 127.0.0.1 to connect to one another
You need to use the container's name instead.

You dont need to map ports unless you want to access thoses ports from the host. the containers in a docker compose have access to each other automatically.

A full working exemple would be a folder containing : docker-compose.yml, node/server.js and node/package.json.
to start it run "npm install" from the node directory
then "docker-compose up"
Then u can use curl or your brower to check its working.
curl http://localhost:3000/
curl http://localhost:3000/save

let me know if you need clarifications on port mapping / host.

here are the files :

package.json
```
{
  "name": "micro",
  "version": "1.0.0",
  "description": "",
  "main": "server.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "node server.js"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "express": "^4.17.1",
    "mongoose": "^5.9.4"
  }
}
```

docker-compose.yml
```
version: "3"
services:
  node:
    command: "node server.js"
    restart: always
    image: node
    working_dir: /home/node/site
    volumes:
      - ./node:/home/node/site
    ports:
      - "3000:3000"
    environment:
      - "MONGO_URL=mongodb://mongo:27017/files"

  mongo:
    image: mongo
    restart: always
    volumes:
      - ./mongo:/data/db

```

node/server.js
```
const express = require('express');
const port = process.env.PORT || 3000;
const app = express();

// mongoose
var mongoose = require('mongoose');

mongoose.connection.on('connected', function() { console.log('connected'); })
mongoose.connection.on('connecting', function() { console.log('connecting'); })
mongoose.connection.on('disconnecting', function() { console.log('disconnecting'); })
mongoose.connection.on('disconnected', function() { console.log('disconnected'); })
mongoose.connection.on('close', function() { console.log('close'); })
mongoose.connection.on('reconnected', function() { console.log('reconnected'); })
mongoose.connection.on('error', function() { console.log('error'); })

mongoose.connect(process.env.MONGO_URL, {
    useNewUrlParser: true,
    useUnifiedTopology: true,
}).catch(err => console.log(err));



// schema
var FileSchema = new mongoose.Schema({
    name : { type: String, required: true, trim: true },
}, {
    timestamps: true
});

// model
var FileModel = mongoose.model('files', FileSchema);

// routes
app.get('/', function(req, res, next) {
    res.send('online');
});

app.get('/save', function(req, res, next) {
    // routes
    var obj = new FileModel({
        name: 'test',
    });

    obj.save(function (err) {
      if (err) return next(err);
      
      res.send(obj);
    });
});

// start server
app.use(function(err, req, res, next) {
    if (err) return res.status(err.status||500).send({error: err.message});

    res.status(404).send('Page not found');
});

app.listen(port, function() {
    console.log('Listening on', port);
});
```

**Comment by fangedhex** [comment]
I've tried to add Docker to myDrive without the network_mode on host : I'm using myself Docker for a lot of softwares I host at home. But I don't know why but in mode host it works and in network bridge, I get a connection reset on my browser with no errors on the server.

So if you have any idea why I can get a connection reset, I can fix it so we can all use bridge mode with Docker :)

**Comment by rafipiccolo** [comment]
Hello, I am stuck in the countryside during the covid. My internet is very bad, i just can checkout the project... shame.

Does my version works for you, or it causes disconnection too ? if it fails, it may be related to your config. if it works then its mydrive code who fails and i could try to read it ?

**Comment by fangedhex** [comment]
I already tried : I made the dockerfile but while testing without host network mode, I couldn't connect to the server and no errors were printed on the server console. It keeps resetting the connection for me. So I put that host network mode until we find something to fix it.

**Comment by Xrunner1** [comment]
@rafipiccolo Stay there, be safe!

**Comment by subnub** [comment]
MyDrive now supports Docker images, so I will close this issue now :)
