### ISSUE TITLE
REMOTE_URL isn't loaded

### ISSUE THREAD

**Issue by mzch** [subnub/myDrive#16]
I build myDrive from master branch, then the following error orrcurred:

<img width="1624" alt="ScreenShot" src="https://user-images.githubusercontent.com/621178/82872446-0823bc00-9f6e-11ea-8c69-8c646afeaba9.png">

It seems not to load REMOTE_URL variable.

Any idea?

**Comment by subnub** [comment]
MyDrive will first open a small web server to accept the encryption key, so you must go to localhost to enter this key, (e.g. http://localhost:5051 in your case) or you can place a key in the servers environment variables (located  in the config folder, the file name is prod.env) with the following format KEY=yourpassword

**Comment by mzch** [comment]
Oh, MyDrive works well as you said. Thanks @subnub !
