### ISSUE TITLE
Downloading file is breaking site

### ISSUE THREAD

**Issue by jagdishjadeja** [subnub/myDrive#17]
download any file is breaking site and navigating to application error page

**Comment by subnub** [comment]
Can I have some more information on this issue please, exactly what error page are you getting, and if you could also show the terminal output when you try to download a file, thank you!

**Comment by jagdishjadeja** [comment]
![Screenshot 2020-06-14 at 8 41 31 PM](https://user-images.githubusercontent.com/17143515/84597156-81cd0c80-ae7f-11ea-9e0a-8ff60f272953.png)

**Comment by subnub** [comment]
Ooh I did not realize you were talking about the demo my bad, so this is intended Downloading is blocked on the demo.
