### ISSUE TITLE
Folder upload is not working

### ISSUE THREAD

**Issue by thatshailesh** [subnub/myDrive#20]
Folder upload is not working

**Comment by subnub** [comment]
Oh yeah folder uploading is not yet implemented, maybe I should either remove the button for now, or add some type of info screen. Thank you for reminding me.

**Comment by thatshailesh** [comment]
@subnub you don't intend to implement it? or can you guide how to implement?

**Comment by subnub** [comment]
@thatshailesh At the moment I do not have any plans on implementing it, there's other things I wanted to add to myDrive first. I briefly explored methods of how to do this earlier but I never found anything concrete so I am sure how do it yet, sorry man. 

That being said I could notify you once folder uploading is added, its just not the top priority at the moment.

**Comment by thatshailesh** [comment]
Ok no problem
Thanks
