### ISSUE TITLE
[Feature request] Default sorting option

### ISSUE THREAD

**Issue by Ghoelian** [subnub/myDrive#27]
I think the option to change the default sorting, which is Last Modified right now, would be a great addition. I would personally prefer to have my files sorted by name over sorting by modified date.

Also, either the ability to change the default sorting direction, or change the default direction to ascending. It seems to default to sorting from z-A by default now.

**Comment by Ghoelian** [comment]
An option to create an alert when the user tries to leave the page while files are still being uploaded might be nice. Maybe even have that on by default.

**Comment by subnub** [comment]
The newest update has a setting to change the default sorting options. So now you can change if it is sorted by name or date, and also acceding or descending order.
