### ISSUE TITLE
Can't run

### ISSUE THREAD

**Issue by ran-j** [subnub/myDrive#34]
I trying to use with docker and tryed with npm run build and got the same error.

![image](https://user-images.githubusercontent.com/17410205/103162250-1c15f180-47cd-11eb-8cf7-5b5a9129fd7f.png)

**Comment by subnub** [comment]
What version are you running? Like if this from the master branch? This is usually caused because the mongoose types are missing. 
'npm i @types/mongoose'
Try this command then rebuild.

**Comment by ran-j** [comment]
I run 'npm i @types/mongoose' and nothing

I cloned branch master
