### ISSUE TITLE
'npm run build' failed

### ISSUE THREAD

**Issue by a8154d** [subnub/myDrive#46]
![1](https://user-images.githubusercontent.com/69576557/115983116-ee518580-a5d1-11eb-828d-7c15accb764f.png)

**Comment by subnub** [comment]
I pushed a hotfix to the master branch, so now this issue should be fixed. You can either run `git pull` or just redownload the zip. If you do run `git pull` you will need to delete the `node_modules` folder, and also delete the `package-lock.json` file (Do not confuse this with `package.json`).

Thank you! 
I am going to close this issue now, but if you are still having issues feel free to reopen it :)
