### ISSUE TITLE
[Feature Request]: Desktop and Mobile clients

### ISSUE THREAD

**Issue by MordechaiHadad** [subnub/myDrive#56]
I want to be able to access my files also directly from my desktop/mobile and not just on my browser

**Comment by oxmc** [comment]
@MordechaiHadad I would recommend using electron for your desktop use case.

It allows you to create a desktop app of a web browser or any html code.

**Comment by hasansultan92** [comment]
@MordechaiHadad If your looking into using JS for this, you can look into React-native as well?
