### ISSUE TITLE
Help needed ! Error 404

### ISSUE THREAD

**Issue by Thithan77** [subnub/myDrive#7]
Hi ! I have a problem using mydrive. The server launch correctly and I can load the web page but I can't connect or create an account and I have this error with Chromium 78.0.3904.108:
```
xhr.js:178 POST http://localhost:3000/undefined/user-service/login 404 (Not Found)
(anonymous) @ xhr.js:178
e.exports @ xhr.js:12
e.exports @ dispatchRequest.js:50
Promise.then (async)
u.request @ Axios.js:61
r.forEach.u.<computed> @ Axios.js:86
(anonymous) @ bind.js:9
(anonymous) @ auth.js:24
(anonymous) @ index.js:8
(anonymous) @ index.js:37
s @ react-dom.production.min.js:14
p @ react-dom.production.min.js:14
(anonymous) @ react-dom.production.min.js:14
y @ react-dom.production.min.js:15
it @ react-dom.production.min.js:52
ot @ react-dom.production.min.js:51
st @ react-dom.production.min.js:52
pt @ react-dom.production.min.js:56
oe @ react-dom.production.min.js:287
ue @ react-dom.production.min.js:23
Zt @ react-dom.production.min.js:70
Qt @ react-dom.production.min.js:69
t.unstable_runWithPriority @ scheduler.production.min.js:19
Uo @ react-dom.production.min.js:122
ne @ react-dom.production.min.js:287
$t @ react-dom.production.min.js:68
auth.js:37 Error: Request failed with status code 404
    at e.exports (createError.js:16)
    at e.exports (settle.js:17)
    at XMLHttpRequest.p.onreadystatechange (xhr.js:61)
```
I don't have any error in the server part.

**Comment by subnub** [comment]
Hello,

So this seems like possibly something is wrong with your config file, I would either try running npm run init again (if you havent created an account yet) Or possible sending me the info whats inside your environment/config file to see if thats the issue. If you would like to send me the file, one is located at the root of the directory, labeled (.env.production, it is a hidden file), and the other is located in /config, under the name prod.env (this one is not hidden). Just please not the prod.env file, has a field labeled password, you should probably make this say something else before posting it publicly!

**Comment by Thithan77** [comment]
Hi !
Here’s my prod.env file:
```
MONGODB_URL=mongodb+srv://**********:*********@**********.mongodb.net/test?retryWrites=true&w=majority
PASSWORD=****************
HTTP_PORT=3000
HTTPS_PORT=8080
URL=192.168.1.16
FULL_URL=192.168.1.16:3000
ROOT=/home/me/drive
```
And env.production:
```
PORT=3000
REMOTE_URL=192.168.1.16:3000
```

**Comment by Thithan77** [comment]
Hi again !
I tried to understand the problem and I found something weird.
The request to `http://192.168.1.16:3000/undefined/user-service/login` don't work and return an error 404 but if I edit and send to `http://192.168.1.16:3000/user-service/login` I have 200 so it works. I think I did a mistake in my config so that `/undefined` is here.
Still looking for what.

**Comment by subnub** [comment]
Hello, 
So I was somewhat able to reproduce this error, so when it asks for the client URL, that REMOTE_URL part, if its an IP address, it still must include http:// so for example, your .env.production file should look as follows. 

PORT=3000
REMOTE_URL=http://192.168.1.16:3000

You can either run npm run init again to change this (just make to to backup and reenter your old password), or you can just go into the .env.production file, and add http:// onto it, i'm not 100% sure if this is your issue, but if I do not add http:// to an ip address, myDrive will not allow my to connect to the backend. 

Please let me know if this resolves it or not.

**Comment by Thithan77** [comment]
It's still not working ! But I really think there is a problem with the `/undefined/`

**Comment by subnub** [comment]
I am just trying to figure out where at /undefined is even coming from. For the userService login the syntax is as follows: currentURL+"/user-service/login", where the currentURL is just the environment variable from .env.production, the REMOTE_URL entry. So I don't see how what /undefined/ could come into play. 

What OS are you on? Also what node.js version are you running?

**Comment by Thithan77** [comment]
I'm using Node v10.15.2 with Raspbian GNU/Linux 10.
It's weird because it's was working the first time I did it.
I'll test it on my real computer tomorrow to see if I have the same error

**Comment by subnub** [comment]
Well that is an older version of Node.js, I would try upgrading to the latest version, which is 13.11.0. I suggest using the node version manager to do this, as it makes switching between Node versions very easy, you can get it here https://github.com/nvm-sh/nvm 
That being said, I did downgrade my node to version 10.15.2, and I still was not able to reproduce your error, but I am using macOS, so seeing you're on Linux (And ARM linux for that matter), updating your node version could potentially fix the issue. But remember to delete your node_modules folder, reinstall the node modules, and then rebuild the application with "npm run build:no-ssl".

**Comment by subnub** [comment]
Closing this due to no response, please reopen if needed.
