### ISSUE TITLE
 "UserService" is a directory in "/services/UserService" and not a  *.js file

### ISSUE THREAD

**Issue by Shakil-is-here** [subnub/myDrive#8]
Hi,
I found it confusing as I was going through the file
            myDrive/src/controllers/user.js 

-----------
const UserService = require("../services/UserService
![Screenshot (677)_LI](https://user-images.githubusercontent.com/44522075/76449645-a768f680-63f6-11ea-9419-5be9a11aa39b.jpg)
")
const UserProvider = new UserService();
-------------

but "UserService.js" is not available here. "UserService" is a directory and contains some "index.js " 
  inside .  Maybe you should check or may be I am somehow wrong.

**Comment by subnub** [comment]
So by default in Javascript if you just point to a folder, It will look for index.js as its default file. So if you just point to a folder, as long as that folder has a file labeled index.js, it will work without any issue. 

Here is a weblink explaining this in greater details, basically its just a neater way to structure your application.  https://alligator.io/react/index-js-public-interfaces/

**Comment by Shakil-is-here** [comment]
thanks for the correction 🙂
